### PR TITLE
Allow support for Python 3.12

### PR DESCRIPTION
**Pull request by Tenzer**
Python 3.12 was released on 2023-10-02, and this extension should work in the new version without any code changes. The configuration for the project, however, doesn't allow it to be installed on Python 3.12, but this fixes that.

Note: This doesn't remove support for Python 3.7 even though that has reached end-of-life. Let me know if you'd like me to remove support for that here as well.

### CODE REVIEW

**Comment by Tenzer** [comment]
The CI run at least shows `frozenlist` needs to be updated - which requires dropping Python 3.7 support, otherwise, Poetry won't select the latest version of the package because they have dropped 3.7 support. I, by the way, noticed b1e949a84cc4fa4d5a49a0d579650a9095c96871, so I guess dropping support for Python 3.7 is okay since it's not being tested anyway.

`yarl` also needs to be updated. https://github.com/aio-libs/yarl/pull/881 has been merged to add support for Python 3.12 but there's no release with those changes yet, so I guess this probably will have to wait until they have made a new release.

**Comment by guilhermef** [comment]
@Tenzer, we can drop 3.7 support. It was already removed from the Thumbor main project.
Thanks for the contribution.

**Comment by guilhermef** [comment]
@Tenzer , I'm removing Python 3.7 on #153

**Comment by Tenzer** [comment]
I got a bit further with this now but hit a couple of other roadblocks:

1. Scipy needs to be updated to at least version 1.11.2 for wheels to be available for Python 3.12 ([release](https://github.com/scipy/scipy/releases/tag/v1.11.2)). It has, however, already dropped support for Python 3.8, meaning we also need to drop Python 3.8 support, otherwise, Poetry won't allow Scipy 1.11.2 to be installed.
2. aiohttp is a dependency of aiobotocore. They do have Python 3.12 support but it's only available as a prerelease in version 3.9.0b0. They are working on getting that released properly, tracked in https://github.com/aio-libs/aiohttp/issues/7675.

**Comment by Tenzer** [comment]
I have rebased the changes and dropped Python 3.8 support in order to get the updated Scipy that works with Python 3.12. Tests are successful for me now.

**Comment by Tenzer** [comment]
Good idea. I have kept the version range the same for Python 3.8 support for now, but we can bump that if you want. Python 3.9+ are using the version of NumPy and SciPy that has 3.12 support.

**Review by guilhermef — APPROVED** [review]

**Comment by guilhermef** [comment]
Thanks for the contribution @Tenzer

**Comment by Tenzer** [comment]
You're welcome!

**Pull request merged**
